export const CREATE = "CREATE";
export const FETCH_ITEM = "FETCH_ITEM";
export const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
export const FETCH_BY_ITEM = "FETCH_BY_ITEM";
export const END_LOADING = "END_LOADING";
export const END_LOADING_ITEM = "END_LOADING_ITEM";
export const START_LOADING = "START_LOADING";
export const START_LOADING_ITEM = "START_LOADING_ITEM";
export const FETCH_ON_SALE = "FETCH_ON_SALE";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE = "DELETE";
export const GET_FAVORITES = "GET_FAVORITES";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const GET_LOGGED_USER = "GET_LOGGED_USER";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const UPDATE_USER = "UPDATE_USER";
export const START_LOADING_USER = "START_LOADING_USER";
export const END_LOADING_USER = "END_LOADING_USER";
export const GET_USERS = "GET_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";

export const ADD_TO_CART = "ADD_TO_CART";
export const DECREASE_CART_AMOUNT = "DECREASE_CART_AMOUNT";
export const INCREASE_CART_AMOUNT = "INCREASE_CART_AMOUNT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DISCOUNT_CART_PRICE = "DISCOUNT_CART_PRICE";
export const SET_CART_PRICE = "SET_CART_PRICE";
export const CHANGE_ITEM_PRICE = "CHANGE_ITEM_PRICE";
export const EMPTY_CART = "EMPTY_CART";

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER = "GET_ORDER";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const CREATE_ORDER = "CREATE_ORDERS";
export const UPDATE_ORDER = "UPDATE_ORDERS";
export const END_LOADING_ORDER_DATA = "END_LOADING_ORDER_DATA";
export const START_LOADING_ORDER_DATA = "START_LOADING_ORDER_DATA";
